spring:
  datasource:
    url: jdbc:postgresql://gondola.proxy.rlwy.net:36761/railway
    username: postgres
    password: AASwOkfKgTMlYXDwyJqMlaXxzymWlOOf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 8080

jwt:
  secret: chunshuiquan-jwt-secret-key-2026-min32chars
  expiration: 604800000

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://api_key:api_secret@cloud_name}

agora:
  appId: ${AGORA_APP_ID:a22e31b0fe1e4e58b8bb9a3094862577}
  appCertificate: ${AGORA_APP_CERTIFICATE:acd9447ac6624c1888cca53100c01e2b}
