-- 用户资料扩展字段
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS education VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS zodiac VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS smoking VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS drinking VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
